apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fabflix
  template:
    metadata:
      labels:
        app: fabflix
    spec:
      containers:
        - name: fabflix-container
          image: juliatjia/fabflix:v9
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_USERNAME
              value: "mytestuser"
            - name: DB_PASSWORD
              value: "My6$Password"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: fabflix-service
spec:
  selector:
    app: fabflix
  ports:
    - name: http
      port: 8080
  type: ClusterIP
